apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-item-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web_item
  template:
    metadata:
      labels:
        app: web_item
    spec:
      containers:
      - name: web-item-container
        image: dusrbpoiiij/ingress_prj_item_nodejs:0.2
        ports:
        - containerPort: 3000
